import 'dotenv/config';

import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import pg from 'pg';

import { loadPgConfig } from '../../src/config.js';

const { Client, Pool } = pg;
const __dirname = dirname(fileURLToPath(import.meta.url));

// The backend schema (with its lineage triggers) lives in the sibling
// pbdb2-migrations repo. Overridable for non-default checkouts / CI.
const DEFAULT_SQL_PATH = join(__dirname, '../../../pbdb2-migrations/postgresql/create_new.sql');

function sslFrom(config) {
  return config.caCertPath ? { ca: readFileSync(config.caCertPath) } : false;
}

/**
 * Provision an ephemeral test database against the PostgreSQL identified by
 * `PG_*`, load `create_new.sql` into it (triggers and all), and return a pool
 * plus a `teardown` that drops it.
 *
 * Returns `{ available: false, reason }` — never throws — when there is no
 * connection or the schema file is missing, so integration tests SKIP cleanly
 * rather than failing on machines without a database.
 */
export async function setupTestDb() {
  const config = loadPgConfig();
  if (!config.configured) {
    return {
      available: false,
      reason: `PG_* not set (missing ${config.missing.join(', ')}); skipping integration tests`,
    };
  }

  const sqlPath = process.env.CREATE_SQL_PATH || DEFAULT_SQL_PATH;
  if (!existsSync(sqlPath)) {
    return { available: false, reason: `create_new.sql not found at ${sqlPath}; set CREATE_SQL_PATH` };
  }

  const ssl = sslFrom(config);
  const adminCfg = {
    host: config.host,
    port: config.port,
    user: config.user,
    password: config.password,
    database: config.database,
    ssl,
  };

  const admin = new Client(adminCfg);
  try {
    await admin.connect();
  } catch (err) {
    return { available: false, reason: `cannot reach PostgreSQL: ${err.message}; skipping` };
  }

  const dbName = `pbdb2_test_${randomBytes(6).toString('hex')}`;
  await admin.query(`CREATE DATABASE "${dbName}"`);
  await admin.end();

  async function dropDatabase() {
    const dropper = new Client(adminCfg);
    await dropper.connect();
    // Drop fails if any session is still attached; close stragglers first.
    await dropper.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE datname = $1 AND pid <> pg_backend_pid()`,
      [dbName],
    );
    await dropper.query(`DROP DATABASE IF EXISTS "${dbName}"`);
    await dropper.end();
  }

  // From here on the database exists, so any failure must drop it rather than
  // leak an orphan (e.g. a broken create_new.sql failing to load).
  const pool = new Pool({ ...adminCfg, database: dbName });
  try {
    await pool.query(readFileSync(sqlPath, 'utf8'));
  } catch (err) {
    await pool.end().catch(() => {});
    await dropDatabase().catch(() => {});
    return { available: false, reason: `failed to load ${sqlPath}: ${err.message}; skipping` };
  }

  async function teardown() {
    await pool.end();
    await dropDatabase();
  }

  return { available: true, pool, dbName, teardown };
}

/**
 * Bootstrap a person row. `persons.authorizer_person_id` is NOT NULL and
 * self-referential, so the very first person authorizes itself (explicit id,
 * the column is GENERATED BY DEFAULT so this is allowed). Resource rows below
 * reference this person as both enterer and authorizer.
 *
 * @returns {Promise<number>} the person id
 */
export async function seedPerson(pool) {
  const { rows } = await pool.query(
    `INSERT INTO persons (id, role_id, person, authorizer_person_id)
     VALUES (1, (SELECT id FROM dictionaries.roles WHERE role = 'Superadmin'),
             '{"name":"Seed Admin"}'::jsonb, 1)
     ON CONFLICT (id) DO NOTHING
     RETURNING id`,
  );
  return rows.length ? rows[0].id : 1;
}

/**
 * Insert a reference row, returning its serial id. Pass `permid` to extend an
 * existing lineage (the triggers handle succession); omit `removed` for a live
 * row.
 */
export async function insertRef(pool, { permid, personId, reference = {}, removed = null }) {
  const { rows } = await pool.query(
    `INSERT INTO refs (permid, authorizer_person_id, enterer_person_id, reference, removed)
     VALUES ($1, $2, $2, $3::jsonb, $4)
     RETURNING id, permid`,
    [permid, personId, JSON.stringify(reference), removed],
  );
  return rows[0];
}
